#!/bin/bash
#accessed from parmanode.com with:
# curl https://parmanode.com/install_parmanode4 | bash

#GLOBAL VARIABLES...
export dn=/dev/null

if [[ -d "/tmp" ]] ; then
    export tmp="/tmp"
elif [[ -d "$HOME/tmp_parmanode" ]] ; then
    export tmp="$HOME/tmp_parmanode" 
else
   mkdir -p $HOME/tmp_parmanode >/dev/null 2>&1
   export tmp="$HOME/tmp_parmanode" 
fi

#FUNCTIONS
function sww {
echo -e "Something went wrong \n$1\n\nHit <enter> to continue\n q to exit."
read choice </dev/tty
case $choice in x|q) exit ;; esac
}


function colours {

export black="\033[30m"
export red="\033[31m"
export green="\033[32m"
export yellow="\033[1;33m"
export blue="\033[34m"
export magenta="\033[35m"
export cyan="\033[36m"
export white="\033[37m"
export reset="\033[0m"
export orange="\033[1m\033[38;2;255;145;0m"
export pink="\033[38;2;255;0;255m"

export bright_black="\033[90m" ; export grey="\033[90m"

export bright_red="\033[91m"
export bright_green="\033[92m"
export bright_yellow="\033[93m"
export bright_blue="\033[94m"
export bright_magenta="\033[95m"
export bright_cyan="\033[96m"
export bright_white="\033[97m"
export blinkon="\033[5m"
export blinkoff="\033[0m"

if [[ $(uname) == "Darwin" ]] ; then export orange="$yellow" 
fi
}


function check_parmanode_exists {
if [[ -d "$HOME/.parmanode4" ]] ; then

    clear

    echo -e "\nParmanode4 seems to already be installed. Updating and exiting.\n"  #update parmanode if it exists...

    if which git >/dev/null ; then
        if ! git config --global user.email ; then git config --global user.email sample@parmanode.com ; fi
        if ! git config --global user.name ; then git config --global user.name Parman ; fi
        cd $HOME/parman_programs/parmanode4 && git config pull.rebase false && git pull >/dev/null 2>&1
    fi

    exit 
fi
}

function yesornoinstallparmanode {
clear
printf "$orange
############################################################$blue
                   P A R M A N O D E ${red}4$orange
############################################################


  Good call on installing Parmanode. This installation 
  will add a few directories and files here and there, 
  and also install some programs that are necessary for 
  Parmanode to function. You will be asked to confirm 
  on the next page.

  If Parmanode${blue}3$orange is installed on your machine, Parmanode${red}4$orange
  will detect that, and any programs you have installed 
  with it, and migrate them across.
    
  Once that is done, Parmanode${red}4$orange will remove Parmanode${blue}3$orange
  for you. If you ever lose your mind and uninstall 
  Parmanode${red}4$orange, it will leave your machine nice and clean.


############################################################
$yellow Hit <enter> to continue or 'q' and <enter> to quit$orange

"
read choice </dev/tty ; clear
case $choice in q|Q) exit ;; esac
}

function check_docker {

which docker >/dev/null && return 0

if [[ $(uname) == "Darwin" ]] ; then

    export MacOSVersion=$(sw_vers | grep ProductVersion | awk '{print $ 2}')
    export MacOSVersion_major=$(sw_vers | grep ProductVersion | cut -d \. -f 1 | grep -Eo '[0-9]+$')
    export MacOSVersion_minor=$(sw_vers | grep ProductVersion | cut -d \. -f 2)
    export MacOSVersion_patch=$(sw_vers | grep ProductVersion | cut -d \. -f 3)

    if [[ $MacOSVersion_major -lt 12 ]] ; then
    clear
    echo -e "
    \r########################################################################################

    \r    Sorry, you need MacOS version 12.0 or later to use Parmanode.

    \r    The main issue is that Parmanode4 needs docker on Macs, and Docker is increasingly
    \r    requiring higher and higher versions of MacOS to function.

    \r    You can still salvage the situation by finding an old version of Docker and 
    \r    manually installing it. Then if you run this Parmanode4 installer again, it will
    \r    detect that docker is already installed and running and won't bother you with
    \r    version detection.

    \r########################################################################################
    \r    Hit <enter> to exit.
    "
    read </dev/tty
    exit 0
    fi
    install_docker_mac

elif [[ $(uname) == "Linux" ]] ; then
    install_docker_linux
fi

}


function install_docker_mac {
#called by check_docker

docker ps >/dev/null && return 0

#Downloads and installs for mac

if [[ $(uname -m) == "arm64" ]] ; then
download_docker_file="https://desktop.docker.com/mac/main/arm64/Docker.dmg"
else
download_docker_file="https://desktop.docker.com/mac/main/amd64/Docker.dmg"
fi

echo -e "
########################################################################################
$cyan
                               Downloading Docker...
$orange
########################################################################################
please wait
"

#Download Docker Desktop
if [[ ! -f $tmp/docker/Docker.dmg ]] ; then 
    clear
    mkdir -p $tmp/docker
    cd $tmp/docker && curl -LO $download_docker_file 
fi

#Mount and copy to Applications
if [[ -f $tmp/docker/Docker.dmg ]] ; then 
    hdiutil attach $tmp/docker/Docker.dmg
    sleep 3
    sudo cp -r /Volumes/Docker/Docker.app /Applications 
    diskutil unmount /Volumes/Docker
else
    echo -e "\nDocker.dmg does not exist, can't attach as volume. Aborting.\n"
    exit
fi

nohup open -a "Docker Desktop" >$dn 2>&1 & 

while true ; do
if docker ps >$dn 2>&1  ; then return 0 ; fi
clear ; echo -e "$orange
########################################################################################$green
                         DOCKER$orange is starting, please wait...
########################################################################################

    Docker should be loading; it sometimes could take a minute or so. There may be a
    graphical pop-up: Make sure to accept the terms and conditions if that appears,
    otherwise Parmanode (& Docker) will not work. 

    If there's a problem after a few minutes, try starting Docker yourself. If you
    still have issues installing Docker using Parmanode, try installing Docker
    manually yourself. Parmanode will detect it and use it.
    
    After accepting the terms, you can close the Docker WINDOW. 

    If Parmanode doesn't successfully install Docker, and you fail to as well, then
    carefully place the computer in the bin and buy a new one, preferably Linux, 
    not Mac, and not, God forbid, Windows.

$red
               ####################################################
                 HIT <ENTER> ONCE YOU CONFIRMED DOCKER IS RUNNING 
               ####################################################
$orange
   If you hit <enter> too early, this text will loop. To abort, hit 'q' and <enter>

########################################################################################
"
read choice </dev/tty
case $choice in Q|q|Quit|QUIT) exit 0 ;; *) clear ; continue ;; 
esac 
done

return 0
}

function install_docker_linux {
clear ; echo -e "$orange
########################################################################################
$cyan
                                     DOCKER
$orange 
    Docker is a technology that allows software applications to be packaged and run 
    in a way that is more efficient and portable. With Docker, developers can create 
    "containers" that include all the necessary parts of an application, such as the 
    code, operating system, and other dependencies. These containers are like mini
    virtual computers that run inside real computers.

    Docker is required to run some Apps that Parmanode can install for you.

    Hit <enter> to continue and install, and type 'skip' and <enter> to skip it.

########################################################################################
"
read choice </dev/tty ; case $choice in skip) return 0 ;; esac

clear
echo -e "${green}Cleaning up first...\n"

    sudo apt-get purge docker docker-engine docker.io containerd runc docker-ce \
    docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin \
    docker-ce-rootless-extras -y

# download_docker_linux
sudo apt-get update -y
sudo apt-get install ca-certificates curl gnupg -y
sudo install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --yes --dearmor -o /etc/apt/keyrings/docker.gpg
sudo chmod a+r /etc/apt/keyrings/docker.gpg
sudo apt-get update -y

source /etc/os-release 

    if grep -q UBUNTU_CODENAME /etc/os-release ; then 
    CODENAME=$UBUNTU_CODENAME
    else
    CODENAME=$DEBIAN_CODENAME
    fi

    #url ID value tweaking...
    if [[ $NAME == LMDE ]] ; then
        ID=debian #for docker url
        parmanode_conf_add "ID=debian"
    elif [[ $ID == linuxmint ]] ; then 
        debug "ID, 1.5, in linux mint. ID=$ID"
        ID=ubuntu
        parmanode_conf_add "ID=ubuntu"
    else
        ID=$ID
        parmanode_conf_add "ID=$ID"
    fi

echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/$ID $(echo $CODENAME) stable" | \
sudo tee /etc/apt/sources.list.d/docker.list >$dn 

#fix ubuntu label to debian if needed:
if [[ $ID == "debian" ]] ; then 
    sudo sed -i 's/ubuntu/debian/g' /etc/apt/sources.list.d/docker.list >> $dp/sed.log 2>&1
fi

sudo apt-get update -y

sudo apt-get install containerd.io docker-ce docker-ce-cli docker-buildx-plugin docker-compose-plugin docker-compose -y 

sudo usermod -aG docker $USER 

clear ; echo -e "$orange
######################################################################################## 

    In order for Docker to run properly, the computer must be restarted.

    But not now, just remember to do it later before running Parmanode.
    
########################################################################################
    Hit <enter> to continue
"
case $choice in q|Q) exit 0 ;; esac
return 0
}

function make_desktop_text {
#make desktop text document...
if [[ ! -e $HOME/Desktop/parmanode4_info.txt ]] ; then
cat <<'EOF' | tee $HOME/Desktop/run_parmanode4.txt >/dev/null

To run Parmanode, simply open a browser and visit:

http://parmanode4.local:58000

Good idea to bookmark that address, then you can delete this text document.
EOF

echo "See new text document on Desktop."
fi
}


function install_homebrew {

if ! [[ $(uname) == "Darwin" ]] ; then return 0 ; fi
if which brew >/dev/null ; then return 0 ; fi

clear
while true ; do
echo -e "
########################################################################################$cyan
                              HOMEBREW INSTALLATION$orange
########################################################################################

    Homebrew is$red necessary$orange to run Parmanode4. It is a package (software install) 
    manager for MacOS. 

    This can take a while, sometimes with very litte feedback during the process. 

    You may or may not need to respond to some prompts; if there is a recommendation 
    to run a command related to 'git unshallow', then follow that instruction.

    If this fails, you can try to look up instructions to install HomeBrew on your
    Mac yourself, and try the Parmanode4 installation again.

    Proceed or abort? 
$green
                             y)$orange    Install Homebrew
$red
                             n)$orange     Skip (exit)

########################################################################################    
"
read choice </dev/tty ; clear
case $choice in
q|Q) exit ;; n|No|no) exit ;; 
y|Y|yes)

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" 

echo "PATH=/opt/homebrew/bin:\$PATH" | sudo tee -a $HOME/.zshrc >$dn 2>&1

echo -e "\n\nYou may get a prompt to update the PATH - don't worry, Parmanode has done 
it for you.\n\nHit <enter> to continue."

sleep 4

return 0
;;
*)
clear
echo -e "Invalid choice. Hit <enter> then try again."
;;
esac
done
}

function install_homebrew_packages {

if ! [[ $(uname) == "Darwin" ]] ; then return 0 ; fi

brew update

brew install git
brew install bash
brew install netcat
brew install jq
brew install vim
brew install tmux
brew install tor
brew install gnu-sed
brew install gsed
brew install nginx
brew install fcgiwrap
brew install autoconf automake fcgi

#build fastcgi
if ! which fcgiwrap >/dev/null ; then
git clone https://github.com/gnosek/fcgiwrap.git $tmp/fcgiwrap
cd $tmp/fcgiwrap
autoreconf -i
./configure
make
sudo make install
grep -q "/usr/local/sbin" <<<$PATH || echo -e '#ADDED by Parmanode4 ...start flag
export PATH="/usr/local/sbin:$PATH"
#ADDED by Parmanode4 ...end flag' >> ~/.zshrc
source ~/.zshrc
fi

}

function install_linux_packages {

if [[ $(uname) == "Darwin" ]] ; then return 0 ; fi

sudo apt-get update -y
sudo apt-get install -y nginx-full python3 python3-pip socat vim nano ssh || sww
sudo apt-get install -y net-tools git procps tmux x11-apps netcat-traditional jq || sww
sudo apt-get install -y fcgiwrap unzip tor ufw mdadm e2fsprogs e2fsprogs fuse3 libfuse2 || sww
#sudo  apt-get install-y curl gnupg ca-certificates #installed with docker already
{ pip3 install websockets 2>$dn || pip3 install websockets --break-system-packages ; } || sww
}

function gsed_symlink {
if [[ $(uname) == "Linux" ]] && ! which gsed >/dev/null 2>&1 ; then
    sudo ln -s $(which sed) /usr/bin/gsed 
fi
}

function parmanode_directories {
#Check files and directories exist
mkdir -p $HOME/parman_programs
mkdir -p $HOME/parmanode4_apps
mkdir -p $HOME/.parmanode4
touch    $HOME/.parmanode4/installed.conf
touch    $HOME/.parmanode4/parmanode.conf
touch    $HOME/.parmanode4/parmanode.log
touch    $HOME/.parmanode4/debug.log
touch    $HOME/.parmanode4/temp
return 0
}

function  configure_git {
    if ! git config --global user.email ; then git config --global user.email parman@parmanode.com ; fi
    if ! git config --global user.name ; then git config --global user.name parmanode_user ; fi
}

function clone_parmanode {
git clone https://github.com/armantheparman/parmanode4.git $HOME/parman_programs/parmanode4 2>$dn
cd $HOME/parman_programs/parmanode4 && git config pull.rebase false >$dn 2>&1
}

function make_parmanode_service_file {
if [[ $OS != "Linux" ]] ; then return 0 ; fi

cat <<EOF | sudo tee /etc/systemd/system/parmanode.target >$dn 2>&1 #groups services, looks for  parmanode.target.wants
[Unit]
Description=Parmanode Group
EOF

sudo mkdir -p /etc/systemd/system/parmanode.target.wants >$dn 2>&1 #symlinks go here
sudo mkdir -p /etc/systemd/system/parmanode >$dn 2>&1 #service files go here

echo "[Unit]
Description=Parmanode JavaScript Server
After=network.target

[Service]
ExecStart=python3 -m http.server 58002 --directory=$HOME/parman_programs/parmanode4/parmaview/js/
KillMode=process

[Install]
WantedBy=multi-user.target
" | sudo tee /etc/systemd/system/parmanode/pn4_js.service >$dn 2>&1

sudo ln -s /etc/systemd/system/parmanode.target /etc/systemd/system/multi-user.target.wants/parmanode.target >$dn 2>&1
sudo ln -s /etc/systemd/system/parmanode/pn4_js.service /etc/systemd/system/parmanode.target.wants/pn4_js.service >$dn 2>&1
sudo systemctl daemon-reload
sudo systemctl enable --now pn4_js.service >$dn 2>&1

}


function install_parmaview {

if [[ $(uname) == "Darwin" ]] ; then return 0 ; fi

#CGI
sudo systemctl disable fcgiwrap >$dn 2>&1 #in case it is running (needs modification)
sudo mkdir -p /etc/systemd/system/fcgiwrap.service.d
cat<<EOS | sudo tee /etc/systemd/system/fcgiwrap.service.d/override.conf >$dn 2>&1
[Service]
User=$USER
Group=$USER
EOS
sudo systemctl enable --now fcgiwrap


#Nginx
if ! [[ $silent == "true" ]] ; then
netstat -tuln 2>$dn | grep -q :58000 && { sww "Port 58000 is already in use. Proceed with caution." ; }
fi

    #SCRIPT_FILENAME neessary for fcgiwrap to know what to execute
    #Other variables are for the script

cat <<EOF | sudo tee $parmaviewnginx >$dn 2>&1
server {
    #version 1
    listen 58000;
    server_name localhost parmanodl.local parmadrive.local parmanode.local ;
    root $wwwparmaviewdir;
    index index.html;

    location ~ /cgi-bin/.*\.sh {
        fastcgi_split_path_info ^(/.*\.sh)(/.*)?$;
        include fastcgi_params;
        fastcgi_pass unix:/var/run/fcgiwrap.socket;
        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
        fastcgi_param PATH_INFO \$fastcgi_path_info;
        fastcgi_param HOME $HOME;
    }

    location /ws/ {
        proxy_pass http://127.0.0.1:58001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;

    }

    location / {
        index index.html;
        try_files \$uri \$uri/ =404;
    }
}
EOF
sudo systemctl restart nginx

#Mount to directory accessible by www-data (nginx)
sudo mkdir -p $wwwparmaviewdir
sudo mount --bind $HOME/parman_programs/parmanode4/parmaview/ $wwwparmaviewdir || sww "Mounting cgi-bin failed."
sudo mkdir -p /run/parmanode
sudo chmod 2771 /run/parmanode
sudo chown parman:www-data /run/parmanode

}

function do_install {
colours
check_parmanode_exists
yesornoinstallparmanode
check_docker
install_homebrew
install_homebrew_packages
install_linux_packages
gsed_symlink 
parmanode_directories
configure_git 
clone_parmanode
make_desktop_text
make_parmanode_service_file
install_parmaview #set up for Linux only at this stage
}

#migrate_from_parmanode3
function test_parmanode4_install {

unset tests_all_passed

function swwtest {
echo -e "Something went wrong \n$1\n\nHit <enter> to continue\n q to exit."
read choice </dev/tty
export tests_all_passed="false"
case $choice in x|q) exit ;; esac
}

#source files
for file in $HOME/parman_programs/parmanode4/src/**/*.sh ; do
source $file
done
parmanode_variables


clear
echo -e "Testing installation. Please wait..." ; sleep 1.5

docker ps >$dn || { echo -e "\n    Docker not detected. Either it didn't install properly, or the
    the computer needs a little reboot. Hit <enter> to continue tests." ; read </dev/tty ; }

test -d $HOME/parman_programs || swwtest "no parman_programs"
test -d $HOME/parman_programs/parmanode4 || swwtest "no parman_programs/parmanode4"
test -d $HOME/.parmanode4 || swwtest "no $HOME/.parmanode4"
sudo test -d $wwwparmaviewdir || swwtest "no $wwwparmaviewdir"
sudo test -d /run/parmanode || swwtest "/run/parmanode directory not found"

[[ $(uname) == "Darwin" ]] && ! which brew && { echo -e "HomeBrew not detected. Maybe try installing it yourself. 
    Hit <enter> to continue tests." ; read </dev/tty ; }

which netcat >$dn || swwtest "netcat not detected."
which jq >$dn || swwtest "jq not detected."
which vim >$dn || swwtest "vim not detected."
which socat >$dn || swwtest "socat not detected."
which nano >$dn || swwtest "nano not detected."
which ssh >$dn || swwtest "ssh not detected."
which nc >$dn || swwtest "nc not detected."
which tmux >$dn || swwtest "tmux not detected."
which unzip >$dn || swwtest "unzip not detected."
which tor >$dn || swwtest "tor not detected."
which gsed >$dn || swwtest "gsed not detected."
sudo which nginx >$dn || swwtest "nginx not detected."
which python3 >$dn || swwtest "Python3 not detected"
which pip3 >$dn || swwtest "pip3 not detected"
pip3 list | grep -q websockets || swwtest "websockets not detected in pip3 list"

[[ $(uname) == "Linux" ]] && { 
    sudo ls /usr/sbin/fcgiwrap >$dn 2>&1 || swwtest "fcgiwrap not detected."
    sudo systemctl status fcgiwrap >$dn 2>&1 || swwtest "fcgiwrap not running"
    sudo systemctl status pn4_js >$dn 2>&1 || swwtest "parmanode js service not running"
}

[[ $(uname) == "Darwin" ]] && { source $bashrc >$dn 2>&1 ; grep -q /usr/local/sbin <<<$PATH || sww "/usr/local/sbin not in PATH" ; }

sudo test -f $parmaviewnginx || swwtest "parmaviewnginx file not detected"

sudo systemctl status nginx >$dn 2>&1 || swwtest "nginx not running"
return 0
}
##############################################################################################################################
#run it!
##############################################################################################################################

which docker >/dev/null || export reboot="\r    Please reboot before using Parmanode.\n\n\n"

do_install

test_parmanode4_install

    if [[ $tests_all_passed != "false" ]] ; then
        clear
        echo -e "\n\n\n\r    SUCCESS! \n\n\n$reboot"
        sleep 1.5
    else
        echo -e "\n\n\n\r    Install finished, but at least one thing went wrong.\n\n\n"
        sleep 3
    fi

exit

##############################################################################################################################